title: Computational Methods in Imaging Science
description: S2019 BME493/BME593 Washington University in St. Louis
author: Umberto Villa
google_analytics: UA-52448613-4
author_email: uvilla@wustl.edu
theme: jekyll-theme-cayman
mathjax: true
